// File generato da scripts/enea-shadow-runner/generateAnprForeignBirthCountries.mjs.
// Non modificare manualmente: rigenerare dalla fonte ANPR indicata.
export const ANPR_FOREIGN_COUNTRIES_SOURCE = Object.freeze({
  url: "https://docs.italia.it/italia/anpr/anpr/it/stabile/tab/tab_stati_esteri.html",
  sha256: "7ee819b8b1d4e7fbd80432136b7bfc45fde29d0b225cdfe3283374c1eba91687",
  generatedEntryCount: 196,
});

export const ANPR_FOREIGN_BIRTH_COUNTRIES = Object.freeze({
  Z100: Object.freeze({ country: "Albania", selectValue: "alb", sourceId: "anpr-stati-esteri-maeci-z100", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z101: Object.freeze({ country: "Andorra", selectValue: "and", sourceId: "anpr-stati-esteri-maeci-z101", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z102: Object.freeze({ country: "Austria", selectValue: "aut", sourceId: "anpr-stati-esteri-maeci-z102", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z103: Object.freeze({ country: "Belgio", selectValue: "bel", sourceId: "anpr-stati-esteri-maeci-z103", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z104: Object.freeze({ country: "Bulgaria", selectValue: "bgr", sourceId: "anpr-stati-esteri-maeci-z104", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z106: Object.freeze({ country: "Stato della Città del Vaticano", selectValue: "vat", sourceId: "anpr-stati-esteri-maeci-z106", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z107: Object.freeze({ country: "Danimarca", selectValue: "dnk", sourceId: "anpr-stati-esteri-maeci-z107", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z109: Object.freeze({ country: "Finlandia", selectValue: "fin", sourceId: "anpr-stati-esteri-maeci-z109", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z110: Object.freeze({ country: "Francia", selectValue: "fra", sourceId: "anpr-stati-esteri-maeci-z110", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z112: Object.freeze({ country: "Germania", selectValue: "deu", sourceId: "anpr-stati-esteri-maeci-z112", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z114: Object.freeze({ country: "Regno Unito", selectValue: "gbr", sourceId: "anpr-stati-esteri-maeci-z114", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z115: Object.freeze({ country: "Grecia", selectValue: "grc", sourceId: "anpr-stati-esteri-maeci-z115", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z116: Object.freeze({ country: "Irlanda", selectValue: "irl", sourceId: "anpr-stati-esteri-maeci-z116", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z117: Object.freeze({ country: "Islanda", selectValue: "isl", sourceId: "anpr-stati-esteri-maeci-z117", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z119: Object.freeze({ country: "Liechtenstein", selectValue: "lie", sourceId: "anpr-stati-esteri-maeci-z119", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z120: Object.freeze({ country: "Lussemburgo", selectValue: "lux", sourceId: "anpr-stati-esteri-maeci-z120", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z121: Object.freeze({ country: "Malta", selectValue: "mlt", sourceId: "anpr-stati-esteri-maeci-z121", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z123: Object.freeze({ country: "Monaco", selectValue: "mco", sourceId: "anpr-stati-esteri-maeci-z123", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z125: Object.freeze({ country: "Norvegia", selectValue: "nor", sourceId: "anpr-stati-esteri-maeci-z125", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z126: Object.freeze({ country: "Paesi Bassi", selectValue: "nld", sourceId: "anpr-stati-esteri-maeci-z126", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z127: Object.freeze({ country: "Polonia", selectValue: "pol", sourceId: "anpr-stati-esteri-maeci-z127", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z128: Object.freeze({ country: "Portogallo", selectValue: "prt", sourceId: "anpr-stati-esteri-maeci-z128", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z129: Object.freeze({ country: "Romania", selectValue: "rou", sourceId: "anpr-stati-esteri-maeci-z129", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z130: Object.freeze({ country: "San Marino", selectValue: "smr", sourceId: "anpr-stati-esteri-maeci-z130", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z131: Object.freeze({ country: "Spagna", selectValue: "esp", sourceId: "anpr-stati-esteri-maeci-z131", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z132: Object.freeze({ country: "Svezia", selectValue: "swe", sourceId: "anpr-stati-esteri-maeci-z132", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z133: Object.freeze({ country: "Svizzera", selectValue: "che", sourceId: "anpr-stati-esteri-maeci-z133", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z134: Object.freeze({ country: "Ungheria", selectValue: "hun", sourceId: "anpr-stati-esteri-maeci-z134", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z138: Object.freeze({ country: "Ucraina", selectValue: "ukr", sourceId: "anpr-stati-esteri-maeci-z138", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z139: Object.freeze({ country: "Bielorussia", selectValue: "blr", sourceId: "anpr-stati-esteri-maeci-z139", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z140: Object.freeze({ country: "Moldova", selectValue: "mda", sourceId: "anpr-stati-esteri-maeci-z140", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z144: Object.freeze({ country: "Estonia", selectValue: "est", sourceId: "anpr-stati-esteri-maeci-z144", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z145: Object.freeze({ country: "Lettonia", selectValue: "lva", sourceId: "anpr-stati-esteri-maeci-z145", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z146: Object.freeze({ country: "Lituania", selectValue: "ltu", sourceId: "anpr-stati-esteri-maeci-z146", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z148: Object.freeze({ country: "Macedonia, Repubblica di", selectValue: "mkd", sourceId: "anpr-stati-esteri-maeci-z148", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z149: Object.freeze({ country: "Croazia", selectValue: "hrv", sourceId: "anpr-stati-esteri-maeci-z149", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z150: Object.freeze({ country: "Slovenia", selectValue: "svn", sourceId: "anpr-stati-esteri-maeci-z150", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z153: Object.freeze({ country: "Bosnia-Erzegovina", selectValue: "bih", sourceId: "anpr-stati-esteri-maeci-z153", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z154: Object.freeze({ country: "Russa, Federazione", selectValue: "rus", sourceId: "anpr-stati-esteri-maeci-z154", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z155: Object.freeze({ country: "Slovacchia", selectValue: "svk", sourceId: "anpr-stati-esteri-maeci-z155", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z156: Object.freeze({ country: "Ceca, Repubblica", selectValue: "cze", sourceId: "anpr-stati-esteri-maeci-z156", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z158: Object.freeze({ country: "Serbia, Repubblica di", selectValue: "srb", sourceId: "anpr-stati-esteri-maeci-z158", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z159: Object.freeze({ country: "Montenegro", selectValue: "mne", sourceId: "anpr-stati-esteri-maeci-z159", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z160: Object.freeze({ country: "Kosovo", selectValue: "kos", sourceId: "anpr-stati-esteri-maeci-z160", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z161: Object.freeze({ country: "Territori dell’Autonomia Palestinese", selectValue: "pse", sourceId: "anpr-stati-esteri-maeci-z161", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z200: Object.freeze({ country: "Afghanistan", selectValue: "afg", sourceId: "anpr-stati-esteri-maeci-z200", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z203: Object.freeze({ country: "Arabia Saudita", selectValue: "sau", sourceId: "anpr-stati-esteri-maeci-z203", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z204: Object.freeze({ country: "Bahrein", selectValue: "bhr", sourceId: "anpr-stati-esteri-maeci-z204", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z205: Object.freeze({ country: "Bhutan", selectValue: "btn", sourceId: "anpr-stati-esteri-maeci-z205", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z206: Object.freeze({ country: "Myanmar (ex Birmania)", selectValue: "mmr", sourceId: "anpr-stati-esteri-maeci-z206", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z207: Object.freeze({ country: "Brunei", selectValue: "brn", sourceId: "anpr-stati-esteri-maeci-z207", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z208: Object.freeze({ country: "Cambogia", selectValue: "khm", sourceId: "anpr-stati-esteri-maeci-z208", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z209: Object.freeze({ country: "Sri Lanka (ex Ceylon)", selectValue: "lka", sourceId: "anpr-stati-esteri-maeci-z209", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z210: Object.freeze({ country: "Cinese, Repubblica Popolare", selectValue: "chn", sourceId: "anpr-stati-esteri-maeci-z210", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z211: Object.freeze({ country: "Cipro", selectValue: "cyp", sourceId: "anpr-stati-esteri-maeci-z211", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z213: Object.freeze({ country: "Corea, Repubblica (Corea del Sud)", selectValue: "kor", sourceId: "anpr-stati-esteri-maeci-z213", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z214: Object.freeze({ country: "Corea, Repubblica Popolare Democratica (Corea del Nord)", selectValue: "prk", sourceId: "anpr-stati-esteri-maeci-z214", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z215: Object.freeze({ country: "Emirati Arabi Uniti", selectValue: "are", sourceId: "anpr-stati-esteri-maeci-z215", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z216: Object.freeze({ country: "Filippine", selectValue: "phl", sourceId: "anpr-stati-esteri-maeci-z216", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z217: Object.freeze({ country: "Taiwan (ex Formosa)", selectValue: "twn", sourceId: "anpr-stati-esteri-maeci-z217", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z219: Object.freeze({ country: "Giappone", selectValue: "jpn", sourceId: "anpr-stati-esteri-maeci-z219", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z220: Object.freeze({ country: "Giordania", selectValue: "jor", sourceId: "anpr-stati-esteri-maeci-z220", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z222: Object.freeze({ country: "India", selectValue: "ind", sourceId: "anpr-stati-esteri-maeci-z222", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z223: Object.freeze({ country: "Indonesia", selectValue: "idn", sourceId: "anpr-stati-esteri-maeci-z223", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z224: Object.freeze({ country: "Iran, Repubblica Islamica del", selectValue: "irn", sourceId: "anpr-stati-esteri-maeci-z224", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z225: Object.freeze({ country: "Iraq", selectValue: "irq", sourceId: "anpr-stati-esteri-maeci-z225", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z226: Object.freeze({ country: "Israele", selectValue: "isr", sourceId: "anpr-stati-esteri-maeci-z226", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z227: Object.freeze({ country: "Kuwait", selectValue: "kwt", sourceId: "anpr-stati-esteri-maeci-z227", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z228: Object.freeze({ country: "Laos", selectValue: "lao", sourceId: "anpr-stati-esteri-maeci-z228", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z229: Object.freeze({ country: "Libano", selectValue: "lbn", sourceId: "anpr-stati-esteri-maeci-z229", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z232: Object.freeze({ country: "Maldive", selectValue: "mdv", sourceId: "anpr-stati-esteri-maeci-z232", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z233: Object.freeze({ country: "Mongolia", selectValue: "mng", sourceId: "anpr-stati-esteri-maeci-z233", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z234: Object.freeze({ country: "Nepal", selectValue: "npl", sourceId: "anpr-stati-esteri-maeci-z234", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z235: Object.freeze({ country: "Oman", selectValue: "omn", sourceId: "anpr-stati-esteri-maeci-z235", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z236: Object.freeze({ country: "Pakistan", selectValue: "pak", sourceId: "anpr-stati-esteri-maeci-z236", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z237: Object.freeze({ country: "Qatar", selectValue: "qat", sourceId: "anpr-stati-esteri-maeci-z237", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z240: Object.freeze({ country: "Siria", selectValue: "syr", sourceId: "anpr-stati-esteri-maeci-z240", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z241: Object.freeze({ country: "Thailandia", selectValue: "tha", sourceId: "anpr-stati-esteri-maeci-z241", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z242: Object.freeze({ country: "Timor Orientale", selectValue: "tls", sourceId: "anpr-stati-esteri-maeci-z242", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z243: Object.freeze({ country: "Turchia", selectValue: "tur", sourceId: "anpr-stati-esteri-maeci-z243", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z246: Object.freeze({ country: "Yemen", selectValue: "yem", sourceId: "anpr-stati-esteri-maeci-z246", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z247: Object.freeze({ country: "Malaysia", selectValue: "mys", sourceId: "anpr-stati-esteri-maeci-z247", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z248: Object.freeze({ country: "Singapore", selectValue: "sgp", sourceId: "anpr-stati-esteri-maeci-z248", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z249: Object.freeze({ country: "Bangladesh", selectValue: "bgd", sourceId: "anpr-stati-esteri-maeci-z249", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z251: Object.freeze({ country: "Vietnam", selectValue: "vnm", sourceId: "anpr-stati-esteri-maeci-z251", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z252: Object.freeze({ country: "Armenia", selectValue: "arm", sourceId: "anpr-stati-esteri-maeci-z252", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z253: Object.freeze({ country: "Azerbaigian", selectValue: "aze", sourceId: "anpr-stati-esteri-maeci-z253", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z254: Object.freeze({ country: "Georgia", selectValue: "geo", sourceId: "anpr-stati-esteri-maeci-z254", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z255: Object.freeze({ country: "Kazakhstan", selectValue: "kaz", sourceId: "anpr-stati-esteri-maeci-z255", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z256: Object.freeze({ country: "Kirghizistan", selectValue: "kgz", sourceId: "anpr-stati-esteri-maeci-z256", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z257: Object.freeze({ country: "Tagikistan", selectValue: "tjk", sourceId: "anpr-stati-esteri-maeci-z257", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z258: Object.freeze({ country: "Turkmenistan", selectValue: "tkm", sourceId: "anpr-stati-esteri-maeci-z258", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z259: Object.freeze({ country: "Uzbekistan", selectValue: "uzb", sourceId: "anpr-stati-esteri-maeci-z259", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z300: Object.freeze({ country: "Namibia", selectValue: "nam", sourceId: "anpr-stati-esteri-maeci-z300", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z301: Object.freeze({ country: "Algeria", selectValue: "dza", sourceId: "anpr-stati-esteri-maeci-z301", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z302: Object.freeze({ country: "Angola", selectValue: "ago", sourceId: "anpr-stati-esteri-maeci-z302", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z305: Object.freeze({ country: "Burundi", selectValue: "bdi", sourceId: "anpr-stati-esteri-maeci-z305", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z306: Object.freeze({ country: "Camerun", selectValue: "cmr", sourceId: "anpr-stati-esteri-maeci-z306", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z307: Object.freeze({ country: "Capo Verde", selectValue: "cpv", sourceId: "anpr-stati-esteri-maeci-z307", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z308: Object.freeze({ country: "Centrafricana, Repubblica", selectValue: "caf", sourceId: "anpr-stati-esteri-maeci-z308", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z309: Object.freeze({ country: "Ciad", selectValue: "tcd", sourceId: "anpr-stati-esteri-maeci-z309", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z310: Object.freeze({ country: "Comore", selectValue: "com", sourceId: "anpr-stati-esteri-maeci-z310", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z311: Object.freeze({ country: "Congo (Repubblica del)", selectValue: "cog", sourceId: "anpr-stati-esteri-maeci-z311", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z312: Object.freeze({ country: "Congo, Repubblica democratica del (ex Zaire)", selectValue: "cod", sourceId: "anpr-stati-esteri-maeci-z312", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z313: Object.freeze({ country: "Costa d’Avorio", selectValue: "civ", sourceId: "anpr-stati-esteri-maeci-z313", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z314: Object.freeze({ country: "Benin (ex Dahomey)", selectValue: "ben", sourceId: "anpr-stati-esteri-maeci-z314", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z315: Object.freeze({ country: "Etiopia", selectValue: "eth", sourceId: "anpr-stati-esteri-maeci-z315", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z316: Object.freeze({ country: "Gabon", selectValue: "gab", sourceId: "anpr-stati-esteri-maeci-z316", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z317: Object.freeze({ country: "Gambia", selectValue: "gmb", sourceId: "anpr-stati-esteri-maeci-z317", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z318: Object.freeze({ country: "Ghana", selectValue: "gha", sourceId: "anpr-stati-esteri-maeci-z318", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z319: Object.freeze({ country: "Guinea", selectValue: "gin", sourceId: "anpr-stati-esteri-maeci-z319", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z320: Object.freeze({ country: "Guinea Bissau", selectValue: "gnb", sourceId: "anpr-stati-esteri-maeci-z320", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z321: Object.freeze({ country: "Guinea Equatoriale", selectValue: "gnq", sourceId: "anpr-stati-esteri-maeci-z321", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z322: Object.freeze({ country: "Kenya", selectValue: "ken", sourceId: "anpr-stati-esteri-maeci-z322", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z325: Object.freeze({ country: "Liberia", selectValue: "lbr", sourceId: "anpr-stati-esteri-maeci-z325", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z326: Object.freeze({ country: "Libia", selectValue: "lby", sourceId: "anpr-stati-esteri-maeci-z326", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z327: Object.freeze({ country: "Madagascar", selectValue: "mdg", sourceId: "anpr-stati-esteri-maeci-z327", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z328: Object.freeze({ country: "Malawi", selectValue: "mwi", sourceId: "anpr-stati-esteri-maeci-z328", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z329: Object.freeze({ country: "Mali", selectValue: "mli", sourceId: "anpr-stati-esteri-maeci-z329", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z330: Object.freeze({ country: "Marocco", selectValue: "mar", sourceId: "anpr-stati-esteri-maeci-z330", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z331: Object.freeze({ country: "Mauritania", selectValue: "mrt", sourceId: "anpr-stati-esteri-maeci-z331", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z332: Object.freeze({ country: "Mauritius", selectValue: "mus", sourceId: "anpr-stati-esteri-maeci-z332", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z333: Object.freeze({ country: "Mozambico", selectValue: "moz", sourceId: "anpr-stati-esteri-maeci-z333", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z334: Object.freeze({ country: "Niger", selectValue: "ner", sourceId: "anpr-stati-esteri-maeci-z334", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z335: Object.freeze({ country: "Nigeria", selectValue: "nga", sourceId: "anpr-stati-esteri-maeci-z335", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z336: Object.freeze({ country: "Egitto", selectValue: "egy", sourceId: "anpr-stati-esteri-maeci-z336", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z337: Object.freeze({ country: "Zimbabwe (ex Rhodesia)", selectValue: "zwe", sourceId: "anpr-stati-esteri-maeci-z337", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z338: Object.freeze({ country: "Ruanda", selectValue: "rwa", sourceId: "anpr-stati-esteri-maeci-z338", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z341: Object.freeze({ country: "São Tomé e Principe", selectValue: "stp", sourceId: "anpr-stati-esteri-maeci-z341", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z342: Object.freeze({ country: "Seychelles", selectValue: "syc", sourceId: "anpr-stati-esteri-maeci-z342", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z343: Object.freeze({ country: "Senegal", selectValue: "sen", sourceId: "anpr-stati-esteri-maeci-z343", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z344: Object.freeze({ country: "Sierra Leone", selectValue: "sle", sourceId: "anpr-stati-esteri-maeci-z344", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z345: Object.freeze({ country: "Somalia", selectValue: "som", sourceId: "anpr-stati-esteri-maeci-z345", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z347: Object.freeze({ country: "Sud Africa", selectValue: "zaf", sourceId: "anpr-stati-esteri-maeci-z347", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z348: Object.freeze({ country: "Sudan", selectValue: "sdn", sourceId: "anpr-stati-esteri-maeci-z348", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z349: Object.freeze({ country: "Swaziland", selectValue: "swz", sourceId: "anpr-stati-esteri-maeci-z349", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z351: Object.freeze({ country: "Togo", selectValue: "tgo", sourceId: "anpr-stati-esteri-maeci-z351", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z352: Object.freeze({ country: "Tunisia", selectValue: "tun", sourceId: "anpr-stati-esteri-maeci-z352", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z353: Object.freeze({ country: "Uganda", selectValue: "uga", sourceId: "anpr-stati-esteri-maeci-z353", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z354: Object.freeze({ country: "Burkina Faso (ex Alto Volta)", selectValue: "bfa", sourceId: "anpr-stati-esteri-maeci-z354", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z355: Object.freeze({ country: "Zambia", selectValue: "zmb", sourceId: "anpr-stati-esteri-maeci-z355", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z357: Object.freeze({ country: "Tanzania", selectValue: "tza", sourceId: "anpr-stati-esteri-maeci-z357", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z358: Object.freeze({ country: "Botswana", selectValue: "bwa", sourceId: "anpr-stati-esteri-maeci-z358", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z359: Object.freeze({ country: "Lesotho", selectValue: "lso", sourceId: "anpr-stati-esteri-maeci-z359", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z361: Object.freeze({ country: "Gibuti", selectValue: "dji", sourceId: "anpr-stati-esteri-maeci-z361", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z368: Object.freeze({ country: "Eritrea", selectValue: "eri", sourceId: "anpr-stati-esteri-maeci-z368", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z401: Object.freeze({ country: "Canada", selectValue: "can", sourceId: "anpr-stati-esteri-maeci-z401", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z404: Object.freeze({ country: "Stati Uniti d’America", selectValue: "usa", sourceId: "anpr-stati-esteri-maeci-z404", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z502: Object.freeze({ country: "Bahamas", selectValue: "bhs", sourceId: "anpr-stati-esteri-maeci-z502", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z503: Object.freeze({ country: "Costa Rica", selectValue: "cri", sourceId: "anpr-stati-esteri-maeci-z503", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z504: Object.freeze({ country: "Cuba", selectValue: "cub", sourceId: "anpr-stati-esteri-maeci-z504", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z505: Object.freeze({ country: "Dominicana, Repubblica", selectValue: "dom", sourceId: "anpr-stati-esteri-maeci-z505", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z506: Object.freeze({ country: "El Salvador", selectValue: "slv", sourceId: "anpr-stati-esteri-maeci-z506", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z507: Object.freeze({ country: "Giamaica", selectValue: "jam", sourceId: "anpr-stati-esteri-maeci-z507", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z509: Object.freeze({ country: "Guatemala", selectValue: "gtm", sourceId: "anpr-stati-esteri-maeci-z509", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z510: Object.freeze({ country: "Haiti", selectValue: "hti", sourceId: "anpr-stati-esteri-maeci-z510", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z511: Object.freeze({ country: "Honduras", selectValue: "hnd", sourceId: "anpr-stati-esteri-maeci-z511", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z512: Object.freeze({ country: "Belize", selectValue: "blz", sourceId: "anpr-stati-esteri-maeci-z512", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z514: Object.freeze({ country: "Messico", selectValue: "mex", sourceId: "anpr-stati-esteri-maeci-z514", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z515: Object.freeze({ country: "Nicaragua", selectValue: "nic", sourceId: "anpr-stati-esteri-maeci-z515", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z516: Object.freeze({ country: "Panama", selectValue: "pan", sourceId: "anpr-stati-esteri-maeci-z516", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z522: Object.freeze({ country: "Barbados", selectValue: "brb", sourceId: "anpr-stati-esteri-maeci-z522", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z524: Object.freeze({ country: "Grenada", selectValue: "grd", sourceId: "anpr-stati-esteri-maeci-z524", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z526: Object.freeze({ country: "Dominica", selectValue: "dma", sourceId: "anpr-stati-esteri-maeci-z526", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z527: Object.freeze({ country: "Saint Lucia", selectValue: "lca", sourceId: "anpr-stati-esteri-maeci-z527", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z528: Object.freeze({ country: "Saint Vincent e Grenadine", selectValue: "vct", sourceId: "anpr-stati-esteri-maeci-z528", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z532: Object.freeze({ country: "Antigua e Barbuda", selectValue: "atg", sourceId: "anpr-stati-esteri-maeci-z532", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z533: Object.freeze({ country: "Saint Kitts e Nevis", selectValue: "kna", sourceId: "anpr-stati-esteri-maeci-z533", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z600: Object.freeze({ country: "Argentina", selectValue: "arg", sourceId: "anpr-stati-esteri-maeci-z600", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z601: Object.freeze({ country: "Bolivia", selectValue: "bol", sourceId: "anpr-stati-esteri-maeci-z601", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z602: Object.freeze({ country: "Brasile", selectValue: "bra", sourceId: "anpr-stati-esteri-maeci-z602", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z603: Object.freeze({ country: "Cile", selectValue: "chl", sourceId: "anpr-stati-esteri-maeci-z603", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z604: Object.freeze({ country: "Colombia", selectValue: "col", sourceId: "anpr-stati-esteri-maeci-z604", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z605: Object.freeze({ country: "Ecuador", selectValue: "ecu", sourceId: "anpr-stati-esteri-maeci-z605", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z606: Object.freeze({ country: "Guyana", selectValue: "guy", sourceId: "anpr-stati-esteri-maeci-z606", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z608: Object.freeze({ country: "Suriname", selectValue: "sur", sourceId: "anpr-stati-esteri-maeci-z608", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z610: Object.freeze({ country: "Paraguay", selectValue: "pry", sourceId: "anpr-stati-esteri-maeci-z610", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z611: Object.freeze({ country: "Perù", selectValue: "per", sourceId: "anpr-stati-esteri-maeci-z611", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z612: Object.freeze({ country: "Trinidad e Tobago", selectValue: "tto", sourceId: "anpr-stati-esteri-maeci-z612", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z613: Object.freeze({ country: "Uruguay", selectValue: "ury", sourceId: "anpr-stati-esteri-maeci-z613", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z614: Object.freeze({ country: "Venezuela", selectValue: "ven", sourceId: "anpr-stati-esteri-maeci-z614", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z700: Object.freeze({ country: "Australia", selectValue: "aus", sourceId: "anpr-stati-esteri-maeci-z700", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z704: Object.freeze({ country: "Figi", selectValue: "fji", sourceId: "anpr-stati-esteri-maeci-z704", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z711: Object.freeze({ country: "Marshall, Isole", selectValue: "mhl", sourceId: "anpr-stati-esteri-maeci-z711", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z713: Object.freeze({ country: "Nauru", selectValue: "nru", sourceId: "anpr-stati-esteri-maeci-z713", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z719: Object.freeze({ country: "Nuova Zelanda", selectValue: "nzl", sourceId: "anpr-stati-esteri-maeci-z719", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z724: Object.freeze({ country: "Salomone, Isole", selectValue: "slb", sourceId: "anpr-stati-esteri-maeci-z724", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z726: Object.freeze({ country: "Samoa", selectValue: "wsm", sourceId: "anpr-stati-esteri-maeci-z726", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z728: Object.freeze({ country: "Tonga", selectValue: "ton", sourceId: "anpr-stati-esteri-maeci-z728", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z730: Object.freeze({ country: "Papua Nuova Guinea", selectValue: "png", sourceId: "anpr-stati-esteri-maeci-z730", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z731: Object.freeze({ country: "Kiribati", selectValue: "kir", sourceId: "anpr-stati-esteri-maeci-z731", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z732: Object.freeze({ country: "Tuvalu", selectValue: "tuv", sourceId: "anpr-stati-esteri-maeci-z732", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z733: Object.freeze({ country: "Vanuatu", selectValue: "vut", sourceId: "anpr-stati-esteri-maeci-z733", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z734: Object.freeze({ country: "Palau", selectValue: "plw", sourceId: "anpr-stati-esteri-maeci-z734", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z735: Object.freeze({ country: "Micronesia, Stati Federati", selectValue: "fsm", sourceId: "anpr-stati-esteri-maeci-z735", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
  Z907: Object.freeze({ country: "Sud Sudan, Repubblica del", selectValue: "ssd", sourceId: "anpr-stati-esteri-maeci-z907", sourceUrl: ANPR_FOREIGN_COUNTRIES_SOURCE.url, sourceAuthority: "ANPR / MAECI" }),
} as const);
