import {describe,expect,it} from "vitest";
import {decideEneaSession,isAllowedKeepalive,leaseAllowsEneaAction,recordEneaKeepalive,recordServerVerifiedLogout,scheduleEneaKeepalive,startEneaSessionLease,stopOverdueEneaLease} from "./eneaSessionLease";
describe("enea-session-lease-v1",()=>{
 it("riusa la sessione autenticata esistente e non apre una nuova finestra",()=>{const d={existingVisible:true,authenticated:true,sessionId:"session-fixture"};expect(decideEneaSession(d)).toBe("reuse_existing");expect(startEneaSessionLease(d)?.events[0].type).toBe("session_reused");expect(decideEneaSession({...d,authenticated:false})).toBe("login_required");});
 it("registra keepalive innocui e prova server append-only",()=>{const l=startEneaSessionLease({existingVisible:true,authenticated:true,sessionId:"s"})!;const n=recordEneaKeepalive(l,{ok:true,serverVerified:true,method:"GET",surface:"dashboard",action:"read dashboard"});expect(n.events.map(e=>e.type)).toEqual(["session_reused","keepalive_ok","server_session_verified"]);expect(leaseAllowsEneaAction(n)).toBe(true);});
 it("ferma la parte ENEA se keepalive o prova server falliscono",()=>{const l=startEneaSessionLease({existingVisible:true,authenticated:true,sessionId:"s"})!;const n=recordEneaKeepalive(l,{ok:false,serverVerified:false,method:"GET",surface:"summary",action:"read summary",reason:"forced_logout"});expect(n).toMatchObject({status:"stopped",stopReason:"forced_logout"});expect(leaseAllowsEneaAction(n)).toBe(false);});
 it("vieta qualunque azione mutativa, preview, ricevuta e secondo invio nel keeper",()=>{expect(isAllowedKeepalive({method:"POST",surface:"dashboard",action:"read dashboard"})).toBe(false);expect(isAllowedKeepalive({method:"GET",surface:"dashboard",action:"apri anteprima"})).toBe(false);expect(isAllowedKeepalive({method:"HEAD",surface:"summary",action:"richiedi ricevuta"})).toBe(false);expect(isAllowedKeepalive({method:"GET",surface:"dashboard",action:"read dashboard",hasBody:true})).toBe(false);expect(isAllowedKeepalive({method:"GET",surface:"dashboard",action:"secondo invio"})).toBe(false);const l=startEneaSessionLease({existingVisible:true,authenticated:true,sessionId:"s"})!;expect(recordEneaKeepalive(l,{ok:true,serverVerified:true,method:"POST",surface:"dashboard",action:"salva"})).toMatchObject({stopReason:"forbidden_keepalive_action",globalClassification:"blocked"});});
 it("pianifica ogni quattro minuti e blocca ENEA durante un keepalive dovuto",()=>{const l=startEneaSessionLease({existingVisible:true,authenticated:true,sessionId:"s"},new Date("2026-08-14T10:00:00Z"))!;expect(scheduleEneaKeepalive(l,new Date("2026-08-14T10:03:59Z"))).toMatchObject({state:"not_due",queueMayUseEnea:true});expect(scheduleEneaKeepalive(l,new Date("2026-08-14T10:04:00Z"))).toMatchObject({state:"due",queueMayUseEnea:false,nextAction:"read_existing_dashboard"});});
 it("scade senza inferire logout e richiede prova server per login_required",()=>{const l=startEneaSessionLease({existingVisible:true,authenticated:true,sessionId:"s"},new Date("2026-08-14T10:00:00Z"))!;const stopped=stopOverdueEneaLease(l,new Date("2026-08-14T10:05:01Z"))!;expect(stopped).toMatchObject({status:"stopped",stopReason:"lease_expired",globalClassification:"blocked"});expect(stopped.events.at(-1)).toMatchObject({type:"lease_expired"});const loggedOut=recordServerVerifiedLogout(l,"server-401-proof",new Date("2026-08-14T10:05:02Z"));expect(loggedOut).toMatchObject({status:"stopped",stopReason:"server_verified_logout",globalClassification:"login_required"});expect(loggedOut.events.at(-1)).toMatchObject({type:"login_required"});expect(()=>recordServerVerifiedLogout(l," ")).toThrow();});
});
