import crypto from "node:crypto";
import { ENEA_OPERATIONAL_REGISTRY, ENEA_OPERATIONAL_REGISTRY_VERSION, USER_AUTHORIZED_RULE_IDS } from "./operationalRegistry";

export const APR_RULE_TEST_MATRIX_VERSION = "apr-enea-rule-test-matrix-v57" as const;
export interface AprRuleTestEntry {
  key: string;
  rule: string;
  registryRuleIds: readonly string[];
  automaticTests: readonly string[];
}

export const APR_RULE_TEST_MATRIX: readonly AprRuleTestEntry[] = Object.freeze([
  { key: "infissi-third-party-certificate-classification", rule: "Un allegato additional diventa certificato tecnico Infissi di terza parte soltanto quando soddisfa integralmente il profilo dichiarazione formale 5/5 o il profilo DoP strutturata 6/6; parole tecniche, numeri e misure isolati restano additional.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.thirdPartyTechnicalCertificateClassification, USER_AUTHORIZED_RULE_IDS.crmInternalTechnicalDocumentUntrusted], automaticTests: ["infissiTechnicalDocumentClassifier: dichiarazione tecnica completa promossa", "infissiTechnicalDocumentClassifier: additional interno escluso", "infissiTechnicalDocumentClassifier: falso positivo lessicale con trasmittanza e misure escluso", "crmDocumentAnalysis: migrazione semantica idempotente preserva kind e fingerprint"] },
  { key: "infissi-internal-technical-document-untrusted", rule: "Il documento tecnico CRM interno e gli allegati generici non classificati non forniscono mai misure, quantita o specifiche; sono ammesse soltanto fattura e certificato tecnico reale di terza parte.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.crmInternalTechnicalDocumentUntrusted, USER_AUTHORIZED_RULE_IDS.infissiTechnicalSourceResolution], automaticTests: ["infissiOriginalSourcePolicy: fattura e certificato terzo ammessi", "infissiOriginalSourcePolicy: additional interno escluso fail-closed", "infissiAutomaticDocumentEvidence: documento interno allettante non influenza il risultato"] },
  { key: "test-ex-novo-original-sources-only", rule: "Ogni test ricostruisce la pratica ex novo dalle sole fonti originarie ammesse e ignora stato CRM pregresso, risultati operatore e storico ENEA.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.testExNovoOriginalSourcesOnly], automaticTests: ["infissiOriginalSourcePolicy: storico e operatore esclusi", "infissiAutomaticDocumentEvidence: output invariato cambiando fonti storiche escluse"] },
  { key: "documented-product-module-over-label", rule: "Il modulo operativo deriva dai prodotti nelle fonti originarie, non dall'etichetta CRM: persiane/avvolgibili/tende/zanzariere seguono Schermature; serramenti/infissi seguono Infissi; i casi misti conservano entrambe le famiglie.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.documentedProductModuleOverLabel, USER_AUTHORIZED_RULE_IDS.persianaScreening, USER_AUTHORIZED_RULE_IDS.avvolgibileScreening], automaticTests: ["documentedProductRouting: persiana etichettata Infissi -> Schermature", "documentedProductRouting: pratica mista conserva due famiglie", "documentedProductRouting: etichetta solo fallback"] },
  { key: "screening-primary-measurements-operator-routing", rule: "Se la fattura identifica una schermatura ma nessuna fonte primaria riporta le misure fisiche del prodotto, APR non usa le misure della finestra protetta e richiede all'operatore larghezza e altezza/sporgenza.", registryRuleIds: ["system-screening-primary-measurements-operator-routing", USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, "system-apr-operator-intervention-routing"], automaticTests: ["crmLocalPreflight: prodotto senza misure -> missing", "crmLocalPreflight: misure prodotto in fattura -> present", "crmLocalPreflight: sole misure finestra protetta non risolvono il prodotto", "deepCaseReview: blocker misure primarie classificato operatore"] },
  { key: "missing-explicit-advance-invoice-reference", rule: "Se una fattura detrae o richiama esplicitamente una fattura di acconto non acquisita, APR non ricostruisce il totale dalla sola fattura di saldo: richiede la fonte fiscale mancante e riaccoda la pratica dopo l'acquisizione.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.missingInvoiceOperatorRequeue, USER_AUTHORIZED_RULE_IDS.distinctInvoiceNumbersSameCustomerSum, "core-economic-classification", "system-apr-operator-intervention-routing"], automaticTests: ["crmLocalPreflight: acconto citato ma assente richiede operatore", "crmLocalPreflight: acconto presente non blocca", "crmLocalPreflight: totale senza riferimento non genera falso positivo"] },
  { key: "composite-invoice-bank-transfer-page-segmentation", rule: "Un PDF multipagina con fattura e bonifico non viene scartato interamente: APR conserva i segmenti fiscali con marcatori propri, usa il bonifico solo per il controllo incrociato ed esclude fail-closed i segmenti esclusivamente bancari.", registryRuleIds: ["system-composite-invoice-bank-transfer-page-segmentation", "core-economic-classification", "core-gross-triple-reconciliation"], automaticTests: ["crmEneaPayloadAudit: allegato fattura+bonifico conserva righe tecniche e audit", "crmEneaPayloadAudit: allegato solo bonifico non genera righe tecniche", "crmLocalPreflight: stessa segmentazione multipagina"] },
  { key: "draft-payload-mapping-completeness", rule: "Un preflight senza conflitti non e READY se il payload ENEA resta incompleto: il caso diventa riparazione tecnica e non entra nella coda esterna.", registryRuleIds: ["system-draft-payload-mapping-completeness", "system-apr-technical-repair-queue", "core-mapping-complete"], automaticTests: ["crmLocalPreflight: Lucia con fonti economiche verdi ma payload incompleto resta blocked", "deepCaseReview: mapping incompleto classificato technical repair"] },
  { key: "paper-form-birth-date-leading-digit-ocr-repair", rule: "Una data di nascita OCR priva della sola cifra iniziale 1 o con la barra del mese letta come 1 viene ricostruita soltanto quando il CF valido nello stesso modulo e nella fattura concorda su anno, mese e giorno; altrimenti resta invariata e fail-closed.", registryRuleIds: ["system-paper-form-birth-date-leading-digit-ocr-repair", USER_AUTHORIZED_RULE_IDS.fiscalCodeIdentityCrossCheck], automaticTests: ["lineaSolePotitoPolicy: riparazione positiva 8 -> 18", "lineaSolePotitoPolicy: separatore 18 108 1934 -> 18/08/1934", "lineaSolePotitoPolicy: giorno non concordante non modificato", "crmLocalPreflight: Alice Molinaris CF verificato dopo replay"] },
  { key: "mixed-forty-case-reliability-test", rule: "Quaranta pratiche gia lavorate vengono congelate da CRM read-only: esattamente 20 schermature e 20 Infissi da Archiviate/Recensione. APR le esegue in sequenza, isola i casi operatore, preserva idempotenza e misura il tempo end-to-end.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.mixedFortyCaseReliabilityTest, "system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["aprCrmArchivedMixedDiscovery: composizione 20+20, esclusioni, sorteggio e replay", "aprCohortSeed: batch autorizzato da 40", "crmAuthenticatedReadOnly: acquisizione sequenziale da 40"] },
  { key: "foreign-birth-anpr-registry", rule: "Ogni nascita estera verificabile dal CF usa l'intera tabella ANPR/MAECI versionata: nazione selezionata tramite ISO3 ENEA e luogo estero come testo libero; codice assente o incompatibile resta fail-closed.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.foreignBirthAnprRegistry, USER_AUTHORIZED_RULE_IDS.fiscalCodeIdentityCrossCheck], automaticTests: ["operationalRules: 196 codici ANPR univoci e fonte hashata", "mapper: Polonia/Romania/RD Congo", "portalBeneficiary: ISO3 selectValue e luogo estero input", "crmLocalPreflight: estero verificato non bloccato e codice sconosciuto fail-closed"] },
  { key: "infissi-portal-managed-energy-savings", rule: "Il risparmio energetico Infissi e calcolato dal portale ENEA: APR non lo calcola e non lo scrive; il payload locale lo omette e una futura lettura viene soltanto auditata senza mutazione.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiPortalManagedEnergySavings], automaticTests: ["infissiEneaDraftPayload: campo omesso", "infissiEneaDraftPayload: audit read-only del valore ENEA", "infissiOriginalDocumentParser: dry-run senza risparmio"] },
  { key: "infissi-old-window-transmittance-matrix", rule: "La trasmittanza del vecchio infisso deriva dalla combinazione esatta materiale telaio + tipo vetro del form; tutte le 20 combinazioni sono versionate. Dati mancanti, ambigui, non mappabili o dubbi usano il fallback prudenziale 6,0 W/m2K.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiOldWindowTransmittanceMatrix], automaticTests: ["infissiOldWindowTransmittance: 20 combinazioni matrice", "infissiOldWindowTransmittance: mancanti/ambigui/dubbio fallback 6,0", "infissiOriginalDocumentParser: mapping form e audit provenienza"] },
  { key: "infissi-shared-screening-workflow", rule: "Infissi/Serramenti riusano il flusso non tecnico delle schermature; cambia soltanto il tipo intervento in Comma 345A - Interventi sull'involucro. Il mapping tecnico ENEA e la bozza restano disabilitati.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiSharedWorkflow, USER_AUTHORIZED_RULE_IDS.invoiceIdentityOverCustomerForm, USER_AUTHORIZED_RULE_IDS.invoiceWorkDateChronology, USER_AUTHORIZED_RULE_IDS.secondaryHome36PercentAllocation], automaticTests: ["infissiModule: sezioni condivise e Comma 345A", "infissiModule: mapping tecnico e bozza chiusi", "operationalRegistry: stessa baseline schermature salvo intervento"] },
  { key: "infissi-invoice-or-technical-source-resolution", rule: "Per ogni infisso, numero e misure provengono dalla fattura se espliciti, altrimenti dai documenti tecnici originari; la misura esterna complessiva e preferita ma un'altra misura documentata e ammessa e auditata. Ogni pezzo resta 1:1 e le fonti confliggenti non vengono risolte arbitrariamente.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiTechnicalSourceResolution, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality], automaticTests: ["infissiTechnicalSources: fattura completa", "infissiTechnicalSources: fattura e documento complementari", "infissiTechnicalSources: fallback documento tecnico", "infissiTechnicalSources: misura esterna preferita o altra documentata", "infissiTechnicalSources: conflitto fail-closed"] },
  { key: "infissi-invoice-certificate-cardinality", rule: "Se fattura e certificato di trasmittanza dichiarano numeri fisici diversi, APR non inventa o aggrega: registra entrambi con le fonti, richiede intervento operatore e continua la coda.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiInvoiceCertificateCardinality, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality], automaticTests: ["infissiInvoiceCertificateCardinality: discordanza operatore", "infissiInvoiceCertificateCardinality: coincidenza", "infissiInvoiceCertificateCardinality: certificato assente non applicabile"] },
  { key: "infissi-transmittance-fallback", rule: "La trasmittanza esplicita di fattura o documento tecnico prevale; soltanto se assente in tutte le fonti originarie APR usa il fallback 1,3 W/m2K. Valori espliciti discordanti non vengono risolti col fallback.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiTransmittanceFallback, USER_AUTHORIZED_RULE_IDS.infissiTechnicalSourceResolution], automaticTests: ["infissiTechnicalSources: fallback 1,3 se assente", "infissiTechnicalSources: valore esplicito prevalente", "infissiTechnicalSources: conflitto esplicito fail-closed"] },
  { key: "infissi-portal-transmittance-131-to-13", rule: "La precedente autorizzazione specifica 1,31 -> 1,3 resta versionata nello storico ed e ora ricompresa dalla regola generale per ogni valore oltre il massimo ENEA.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiPortalTransmittance131To13], automaticTests: ["infissiEneaDraftPayload: 1,31 fonte -> 1,3 ENEA con audit"] },
  { key: "infissi-portal-transmittance-over-max-to-13", rule: "Se la trasmittanza esplicita del nuovo infisso supera il massimo ENEA 1,3, APR conserva il valore sorgente nell'audit e usa 1,3 nel solo campo portale; valori minori o uguali restano invariati.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiPortalTransmittanceOverMaxTo13], automaticTests: ["infissiEneaDraftPayload: valore oltre massimo -> 1,3 con fonte auditata", "infissiEneaDraftPayload: valori entro massimo invariati"] },
  { key: "infissi-enea-area-rounding", rule: "La superficie esatta resta nel ledger per ogni pezzo; il piano ENEA usa il normale arrotondamento a un decimale in m2 senza aggregare la cardinalita.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiAreaRounding, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality], automaticTests: ["infissiTechnicalSources: superficie esatta e arrotondata a un decimale", "infissiTechnicalSources: confronto arrotondamento ENEA"] },
  { key: "infissi-material-glass-fallbacks", rule: "Per Infissi/Serramenti, materiale e vetro espliciti nelle fonti originarie prevalgono; soltanto se assenti APR usa PVC e vetro a bassa emissione come fallback auditati.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiMaterialGlassFallbacks], automaticTests: ["infissiProductRules: fallback PVC e basso-emissivo", "infissiProductRules: valori espliciti prevalenti"] },
  { key: "infissi-shading-closures-form-flag", rule: "La risposta SI del form alla domanda su infissi, zanzariere o persiane seleziona Chiusure oscuranti; NO lascia il flag vuoto; risposta assente o ambigua richiede operatore.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiShadingClosuresFromForm], automaticTests: ["infissiProductRules: SI selezionato e NO vuoto", "infissiProductRules: risposta assente fail-closed"] },
  { key: "infissi-shading-closure-invoice-order-allocation", rule: "Se gli infissi fisici superano le chiusure oscuranti documentate, i primi N infissi ricevono il flag soltanto quando le righe tecniche conservano l'ordine fattura; con righe da certificato o ordine non provato APR non assegna posizioni e richiede operatore.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.infissiShadingClosureInvoiceOrderAllocation, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality], automaticTests: ["infissiShadingClosureAllocation: 3 infissi/2 chiusure con ordine fattura produce true,true,false", "infissiShadingClosureAllocation: righe tecniche da certificato respinte fail-closed", "infissiShadingClosureAllocation: pattern non applicabile conserva il form e non sovra-alloca", "infissiEneaDraftPayload: audit per riga e ordine fattura"] },
  { key: "vepa-bonus-casa-routing-and-anagraphic-contract", rule: "VEPA e vetrate scorrevoli appartengono esclusivamente a Bonus Casa, mai Ecobonus. Beneficiario, cointestatari, CF, residenza e immobile riusano le regole condivise; i campi specifici Bonus Casa restano bloccati finche il portale non viene osservato e testato.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.vepaBonusCasaRouting, USER_AUTHORIZED_RULE_IDS.invoiceIdentityOverCustomerForm, USER_AUTHORIZED_RULE_IDS.invoiceCoBeneficiaryPortalFlow, USER_AUTHORIZED_RULE_IDS.fiscalCodeIdentityCrossCheck], automaticTests: ["vepaModule: routing Bonus Casa ed Ecobonus vietato", "vepaModule: contratto anagrafico condiviso", "operationalRegistry: mapping portale Bonus Casa fail-closed"] },
  { key: "persiana-screening-family", rule: "Persiana ENEA 1:1: gTot esplicito o fallback 0,08, resistenza termica supplementare 0,17, Metallo/alluminio, Automatico solo con motore e Manuale altrimenti; misure senza unita normalizzate entro limiti ampi di plausibilita refuso (larghezza 500-4000 mm, altezza 450-3200 mm) e superficie finestrata uguale alla superficie prodotto.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.persianaScreening, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, USER_AUTHORIZED_RULE_IDS.formInvoicePortalCardinalityCrossCheck], automaticTests: ["invoiceParser: persiane 1:1, confini e normalizzazione cm/mm", "screeningRules: tipologia Persiana, gTot 0,08 e Rsupp 0,17", "portalScreening: selezione Persiana e compilazione Rsupp", "crmLocalPreflight: attributi, superficie finestrata e misure fail-closed"] },
  { key: "avvolgibile-screening-family", rule: "Avvolgibile identico alla persiana salvo tipologia ENEA Persiane avvolgibili: 1:1, gTot esplicito o fallback 0,08, Rsupp 0,17, Metallo/alluminio, Automatico solo con motore e Manuale altrimenti, stessa normalizzazione entro limiti ampi di plausibilita refuso (larghezza 500-4000 mm, altezza 450-3200 mm) e superficie finestrata uguale al prodotto.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.avvolgibileScreening, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, USER_AUTHORIZED_RULE_IDS.formInvoicePortalCardinalityCrossCheck], automaticTests: ["invoiceParser: avvolgibili 1:1, confini e normalizzazione cm/mm", "screeningRules: tipologia Persiane avvolgibili e attributi persiana", "portalScreening: selezione esatta per etichetta e Rsupp", "crmLocalPreflight: contratto completo e fail-closed"] },
  { key: "single-case-regression-test", rule: "Una pratica gia lavorata puo essere ripetuta in una coorte isolata da uno soltanto con autorizzazione esplicita, nuovo dossier e nuovo ID bozza, sempre tramite APR persistente.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.singleCaseRegressionTest, "system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["aprCohortSeed: singolo repeat-test e storico completo", "aprEneaBrowserWorkerService: minimo coda dinamico pari a uno soltanto per seed autorizzato"] },
  { key: "invoice-work-date-chronology", rule: "La cronologia usa tutte le fatture fiscali uniche: prima fattura per inizio lavori, ultima fattura per fine lavori quando il form non la dichiara.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.invoiceWorkDateChronology, USER_AUTHORIZED_RULE_IDS.missingCompletionDate], automaticTests: ["crmLocalPreflight: prima e ultima fattura finanziaria", "crmEneaPayloadAudit: inizio lavori sovrascritto con fonte auditata"] },
  { key: "screening-surface-material-over-support-structure", rule: "Il materiale ENEA e quello della superficie schermante: alluminio di struttura o supporti non trasforma un telo/tessuto in Misto; un codice tessuto o colore associato al telo e prova corroborante.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.screeningSurfaceMaterialOverSupportStructure, "authorized-22-schermature-materiale"], automaticTests: ["crmLocalPreflight: regressione Tommaso Cecchi struttura alluminio e tessuto Tempotest produce Tessuto"] },
  { key: "explicit-composite-screening-material", rule: "Materiali plurifamiglia producono Misto soltanto quando appartengono esplicitamente alla superficie schermante, mai per il solo materiale della struttura.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.explicitCompositeScreeningMaterial, "authorized-22-schermature-materiale"], automaticTests: ["crmLocalPreflight: lamelle schermanti in alluminio piu telo in tessuto produce Misto"] },
  { key: "explicit-motorized-screening-movement", rule: "Motore o comando motorizzato esplicito produce Automatico anche per pergola o pergotenda e prevale sul fallback.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.explicitMotorizedScreeningMovement, "authorized-16-schermature-meccanismo"], automaticTests: ["crmLocalPreflight: pergotenda motorizzata produce Automatico"] },
  { key: "explicit-technical-surface-precision", rule: "La superficie esplicita della singola schermatura prevale sul calcolo; in sua assenza il prodotto delle misure conserva fino a quattro decimali, senza troncamento a una cifra.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.explicitTechnicalSurfacePrecision, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality], automaticTests: ["invoiceParser: Khemara superfici esplicite", "invoiceParser: Righetti 12 prodotti e superfici", "invoiceParser: Maranesi superficie esplicita", "mapper: precisione superficie da misure"] },
  { key: "learning-closure-gate", rule: "Una correzione di un blocco diventa regola APR soltanto dopo il collegamento completo incidente → ID registro → test verde → fingerprint corrente → bundle installato identico.", registryRuleIds: ["system-apr-learning-closure-gate", "system-atomic-checkpoint-resume"], automaticTests: ["ruleMatrixEvidence: test senza deployment resta non attivo", "ruleMatrixEvidence: bundle diverso viene rifiutato", "apr-rule-activation-cli: copertura ID e SHA-256 installati"] },
  { key: "portal-municipality-controlled-selection", rule: "I Comuni ENEA con autocomplete devono essere selezionati fisicamente dalla lista: testo libero, aria-invalid o mancata rilettura server non valgono come campo compilato.", registryRuleIds: ["core-mapping-complete", "system-operator-block-fail-closed", "system-atomic-checkpoint-resume"], automaticTests: ["portalBeneficiary: Comune selezionato", "portalBuilding: Comune selezionato", "cdpEneaBrowserDriver: Sesto S.Giovanni/Sesto San Giovanni"] },
  { key: "uncertain-save-single-recovery", rule: "Un Salva incerto non e' un successo: APR usa prove server read-only, consente al massimo il recupero idempotente previsto e non duplica bozza, pagina o coda.", registryRuleIds: ["system-operator-block-fail-closed", "system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["uncertainPageSaveEvidence: classificazione prove", "aprEneaBrowserWorker: recupero e nessun terzo Salva", "eneaDraftExecution: ripresa gate finale senza nuovo Salva"] },
  { key: "post-draft-historical-benchmark-readonly", rule: "Dopo una bozza TEST salvata, il PDF ENEA storico puo essere letto soltanto come benchmark isolato: nessun valore puo rientrare nel mapper o correggere la bozza.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.postDraftHistoricalBenchmarkReadOnly, "system-readonly-adapter-contract", "system-atomic-checkpoint-resume"], automaticTests: ["postPilotComparison: benchmark post-bozza autorizzato", "aprHistoricalBenchmark: confronto e isolamento valori storici"] },
  { key: "fifteen-case-intermezzo-repeat", rule: "Quindici schermature CRM, anche gia lavorate, vengono congelate in una nuova coorte; nessun risultato precedente e riusato, le vecchie bozze restano storico intoccabile e i nuovi ID sono tracciati separatamente.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.fifteenCaseIntermezzoRepeat, "system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["aprCrmArchivedScreeningDiscovery: 15 selezionate e checkpoint idempotente", "aprCohortSeed: repeat-test 15 senza gate eliminazione", "eneaDraftExecution: blocco isolato e prosecuzione"] },
  { key: "linea-sole-potito-paper-form", rule: "Solo Linea Sole Potito: il modulo cartaceo sostituisce il form inline; orientamento Sud e superficie finestrata stabile 2,0-2,9 m2 sono fallback, sempre subordinati ai valori espliciti.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.lineaSolePotitoPaperForm, "core-form-first", "core-mapping-complete"], automaticTests: ["lineaSolePotitoPolicy: scope fornitore e modulo", "lineaSolePotitoPolicy: precedenza esplicito e stabilita riavvio", "crmEneaPayloadAudit: metadati campo e ID regola", "invoiceParser: formato Linea Sole Potito"] },
  { key: "narrative-invoice-product-extraction", rule: "Le descrizioni narrative di fattura valgono come righe tecniche: N prodotti diventano N righe 1:1; L/H o L/SP sono normalizzate, il gTot esplicito di chiusura prevale e acconto/saldo non duplicano i prodotti.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.narrativeInvoiceProductExtraction, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, USER_AUTHORIZED_RULE_IDS.formGroupProductInheritance], automaticTests: ["invoiceParser: Roberto Muzzi descrizione narrativa", "localInvoiceSegmentation: saldo narrativo supersede acconto", "operationalRegistry: precedenza e audit narrativo"] },
  { key: "invoice-gross-total-vat-included", rule: "Il totale fattura e' sempre il lordo comprensivo di IVA; nelle fatture multipagina una riga totale isolata vale solo se coincide con imponibile + IVA e con il riepilogo lordo per aliquota.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.invoiceGrossTotalVatIncluded, "core-economic-classification", "core-gross-triple-reconciliation"], automaticTests: ["invoiceParser: totale isolato multipagina", "localInvoiceFinancialEvidence: riepilogo lordo per aliquota", "crmLocalPreflight: Lucia Lagrasta pronta"] },
  { key: "distinct-invoice-numbers-same-customer-sum", rule: "Fatture dello stesso dossier cliente con numeri diversi sono documenti economici distinti: i lordi IVA inclusa riconciliati si sommano automaticamente; l'acconto citato puo deduplicare solo le righe tecniche.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.distinctInvoiceNumbersSameCustomerSum, USER_AUTHORIZED_RULE_IDS.invoiceGrossTotalVatIncluded, "core-gross-triple-reconciliation"], automaticTests: ["financialReconciliation: due fatture OCR distinte sommate", "crmLocalPreflight: acconto e saldo Silvia Magi"] },
  { key: "missing-invoice-operator-requeue", rule: "Fattura mancante: motivo esplicito in Richiesto intervento operatore; una nuova fattura e il ritorno in Pronte da fare riattivano la stessa pratica da nuovo fingerprint.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.missingInvoiceOperatorRequeue, "system-apr-operator-intervention-routing", "system-atomic-checkpoint-resume"], automaticTests: ["crmLocalPreflight: fattura assente/non acquisibile", "operationalRegistry: requeue dopo nuova fonte"] },
  { key: "default-single-unit", rule: "Numero appartamenti assente, vuoto o zero: usare 1; un numero positivo esplicito prevale.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.defaultSingleUnitWhenUnspecified, USER_AUTHORIZED_RULE_IDS.singleUnitBuildingQualification], automaticTests: ["crmLocalPreflight: zero/assente normalizzato a 1", "crmEneaPayloadAudit: pacchetto usa 1"] },
  { key: "invoice-total-over-bank-transfers", rule: "Il totale fatture prevale sui bonifici; commissioni bancarie escluse; operatore solo se il capitale bonificato supera le fatture.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.invoiceTotalOverBankTransfers, "core-economic-classification", "core-gross-triple-reconciliation"], automaticTests: ["bankTransferEvidence: importo/commissioni/totale", "crmLocalPreflight: ricevute escluse dalle fatture"] },
  { key: "mandatory-bank-transfer-invoice-expense-cross-check", rule: "Se esistono bonifici, APR riconcilia capitale, commissioni, lordo, spesa tecnica ed esclusioni. Il totale fatture prevale: capitale leggibile uguale o inferiore e riferimenti incompleti sono auditati senza blocco; operatore soltanto se il capitale supera le fatture o non e leggibile. La dicitura fiscale resta non bloccante.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.mandatoryBankTransferInvoiceExpenseCrossCheck, USER_AUTHORIZED_RULE_IDS.invoiceTotalOverBankTransfers, USER_AUTHORIZED_RULE_IDS.bankTransferTaxReliefLabelNonBlocking, "system-apr-operator-intervention-routing"], automaticTests: ["bankTransferEvidence: riferimenti e tipo agevolazione", "crmLocalPreflight: bonifico parziale/riferimenti incompleti non bloccano", "crmLocalPreflight: capitale superiore o illeggibile richiede operatore"] },
  { key: "operator-structured-question-resume", rule: "Un dato ambiguo genera una domanda diretta con fonte e opzioni controllate; la risposta caso-specifica viene persistita e la stessa pratica riaccodata senza fermare le altre.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.operatorStructuredQuestionResume, "system-apr-operator-intervention-routing", "system-atomic-checkpoint-resume"], automaticTests: ["operatorQuestions: risposta e riaccodamento dopo riavvio", "operatorQuestions: non determinabile resta bloccato"] },
  { key: "ten-case-monday-restart", rule: "Dieci pratiche Archiviate vengono congelate, lavorate una alla volta e riprese senza perdite; un blocco per-pratica non arresta le successive.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.tenCaseMondayRestart, "system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["aprCohortSeed: dieci identita univoche", "crmLocalPreflight: dieci casi con riavvio", "eneaDraftExecution: blocco e prosecuzione"] },
  { key: "random-pilot-five-of-fifteen", rule: "Pilot iniziale: cinque clienti estratti casualmente una sola volta da 15 identità CRM reali univoche e congelati nel checkpoint.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.randomPilotFiveOfFifteen, "system-atomic-checkpoint-resume"], automaticTests: ["pilotSample: 5-su-15", "pilotSample: riavvio/idempotenza", "pilotSample: elenco incompleto o duplicato bloccato"] },
  { key: "source-explicit-over-fallback", rule: "Valore esplicito fattura/form prevale sui fallback.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.pergolaScreening, USER_AUTHORIZED_RULE_IDS.cristalScreening, USER_AUTHORIZED_RULE_IDS.zanzarieraScreening, USER_AUTHORIZED_RULE_IDS.genericAwningScreening], automaticTests: ["localDossierPipeline: explicit gTot", "userAuthorizedPolicies: explicit Cristal/pergola"] },
  { key: "valid-original-document-cf", rule: "Se il CF del form e' invalido, un CF valido di fattura originaria prevale solo con identita anagrafica coerente e senza fonti divergenti.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.validOriginalDocumentFiscalCode], automaticTests: ["operationalRules: CF documentale e segmenti anagrafici", "crmLocalPreflight: CF fattura originaria"] },
  { key: "invoice-identity-over-form", rule: "La fattura originaria prevale sul form per beneficiario e cointestatario: corregge l'identità principale verificata dallo stesso CF, esclude il nome presente solo nel form e include il secondo beneficiario documentato in fattura anche se omesso dal form.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.invoiceIdentityOverCustomerForm, USER_AUTHORIZED_RULE_IDS.invoiceCoBeneficiaryPortalFlow, USER_AUTHORIZED_RULE_IDS.fiscalCodeIdentityCrossCheck], automaticTests: ["crmLocalPreflight: identità principale fattura prevale per CF", "crmLocalPreflight: cointestatario form escluso da fattura", "crmLocalPreflight: cointestatario fattura incluso senza form", "crmEneaPayloadAudit: identità principale con fonte fattura", "portalBeneficiary: contratto persona fisica", "cdpEneaBrowserDriver: Salva persona idempotente", "operationalRegistry: precedenza identita fattura"] },
  { key: "fiscal-code-identity-cross-check", rule: "Il CF documentale richiede checksum e coerenza con nome, cognome, data e sesso; luogo verificato solo con codice Belfiore attendibile; ambiguita' bloccante.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.fiscalCodeIdentityCrossCheck, USER_AUTHORIZED_RULE_IDS.validOriginalDocumentFiscalCode], automaticTests: ["operationalRules: CF completo e parziale", "crmLocalPreflight: CF unico e identita coerente"] },
  { key: "secondary-home-36-percent-allocation", rule: "Abitazione principale NO: per ogni intervento l'intero totale congruo 2025-2026 va nella colonna 36%; il 50% deve risultare zero e il totale invariato dopo l'unico Salva.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.secondaryHome36PercentAllocation, "system-atomic-checkpoint-resume", "system-apr-operator-intervention-routing"], automaticTests: ["portalCalculation: piano generale 36%", "crmLocalPreflight: seconda abitazione non bloccata dal vecchio gate", "cdpEneaBrowserDriver: allocazione 36% salvata e verificata con GET", "operationalRegistry: aliquota 36% generale e auditata"] },
  { key: "completion-date-latest-invoice", rule: "Fine lavori assente: ultima fattura; nei collaudi reali oltre 90 giorni o anno portale incompatibile richiedono intervento operatore, salvo la finestra ufficiale ENEA 2026.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.missingCompletionDate, USER_AUTHORIZED_RULE_IDS.completionOver90OperatorGate, USER_AUTHORIZED_RULE_IDS.completionPortalYearOperatorGate, USER_AUTHORIZED_RULE_IDS.enea2026June25NinetyDayWindow], automaticTests: ["crmLocalPreflight: gate data oltre 90 giorni e anno portale", "crmLocalPreflight: finestra 04/02-24/06 con decorrenza 25/06 e scadenza 23/09"] },
  { key: "cristal-fallback", rule: "Cristal è schermatura; gTot 0,33 solo fallback.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.cristalScreening], automaticTests: ["userAuthorizedPolicies: Cristal fallback/esplicito"] },
  { key: "pergola-fallback", rule: "Pergola gTot 0,08 solo in assenza di valore esplicito.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.pergolaScreening], automaticTests: ["localDossierPipeline: pergola esplicita", "userAuthorizedPolicies: pergola fallback"] },
  { key: "zanzariera-fallbacks", rule: "Zanzariera: altra schermatura, Misto/Manuale/0,33 solo fallback.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.zanzarieraScreening], automaticTests: ["localDossierPipeline: zanzariere"] },
  { key: "screening-fallback-material-category-guard", rule: "Una schermatura riconosciuta come zanzariera non puo essere draftReady se il materiale derivato da fallback e diverso da Misto; il conflitto invalida il payload e blocca la bozza senza correzione silenziosa.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.screeningFallbackMaterialCategoryGuard, USER_AUTHORIZED_RULE_IDS.zanzarieraScreening], automaticTests: ["crmLocalPreflight: zanzariera con fallback Misto passa", "crmLocalPreflight: zanzariera generica con fallback Tessuto invalida draftReady"] },
  { key: "physical-cardinality", rule: "Una riga tecnica per prodotto fisico; quantità e aree mai aggregate. Form, fattura, piano APR e riepilogo server sono incrociati; la fattura prevale solo se la differenza è risolta senza ambiguità, altrimenti operatore.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, USER_AUTHORIZED_RULE_IDS.formGroupProductInheritance, USER_AUTHORIZED_RULE_IDS.formInvoicePortalCardinalityCrossCheck, "system-final-draft-source-cardinality-and-cost-verification"], automaticTests: ["productCardinalityPolicy", "invoiceParser: gruppo Vans Seleni 8 prodotti", "crmLocalPreflight: tipo fattura prevalente sul gruppo form", "crmLocalPreflight: differenza form/fattura risolta o bloccata", "cdpEneaBrowserDriver: riepilogo finale 1:1 e costo", "localInvoiceSegmentation: acconto/saldo Seleni senza duplicazione", "localDossierPipeline: cardinalità inclusi/esclusi"] },
  { key: "invoice-header-identity-over-body-reference", rule: "Numero e data dell'intestazione fiscale identificano la fattura; i riferimenti ad acconti/saldi nel corpo non possono sostituirli. Copie con stesso numero/data/totale sono deduplicate prima di cardinalità e importi.", registryRuleIds: ["system-invoice-header-identity-over-body-reference", USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, USER_AUTHORIZED_RULE_IDS.invoiceGrossTotalVatIncluded], automaticTests: ["invoiceParser: intestazione OCR sfalsata prevale sul riferimento acconto", "localInvoiceSegmentation: copie OCR della stessa fattura deduplicate", "crmLocalPreflight: sourceId duplicato auditato"] },
  { key: "bundled-professional-expense", rule: "Una voce professionale compresa nel lordo non diventa automaticamente spesa tecnica: serve ripartizione documentata o risposta operatore caso-specifica; altrimenti la pratica si blocca senza fermare la coda.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.bundledProfessionalExpenseSeparation, USER_AUTHORIZED_RULE_IDS.operatorStructuredQuestionResume, "system-apr-operator-intervention-routing"], automaticTests: ["crmLocalPreflight: Pratica ENEA compresa non quantificata blocca", "crmLocalPreflight: Elisa 1250 senza esclusioni, caso-specifico non propagabile", "operationalRegistry: separazione professionale fail-closed"] },
  { key: "vepa-deferred-current-phase", rule: "Vetrate scorrevoli/VEPA riconosciute e conservate 1:1, ma parcheggiate senza bozza finché il modulo APR VEPA non è verificato e attivato.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.vepaDeferredCurrentPhase, USER_AUTHORIZED_RULE_IDS.technicalProductCardinality, "system-apr-operator-intervention-routing"], automaticTests: ["invoiceParser: vetrata scorrevole Vans", "operationalRegistry: VEPA parcheggiata", "crmLocalPreflight: blocker VEPA esplicito"] },
  { key: "single-house-floors", rule: "Casa singola/unità unica resta tale anche con tre o più piani.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.singleUnitBuildingQualification], automaticTests: ["localDossierPipeline: unità unica tre piani"] },
  { key: "explicit-multi-unit-primary-source-only", rule: "La classificazione plurima richiede una fonte primaria che dichiari esplicitamente condominio o più unità; una fascia di piani non supera unità=1/casa singola.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.explicitBuildingTypeOverAffectedUnitCount, USER_AUTHORIZED_RULE_IDS.singleUnitBuildingQualification], automaticTests: ["crmLocalPreflight: Federigo Cileo oltre tre piani e una unità resta unita unica", "crmEneaPayloadAudit: tipologia e ambito unita unica"] },
  { key: "rinaldi-scoped", rule: "Solo Rinaldi: massimo detraibile esplicito; pergola Eco separata da VEPA.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.rinaldiExplicitDeductibleTotal, USER_AUTHORIZED_RULE_IDS.rinaldiPergolaVepaTestEcobonus], automaticTests: ["rinaldiFinancialPolicies", "localDossierPipeline: Rinaldi misto"] },
  { key: "test-stop-before-external", rule: "Le prove producono solo il piano locale; preview, submit e comunicazioni vietati.", registryRuleIds: [USER_AUTHORIZED_RULE_IDS.testStopAtSavedDraft, "system-readonly-adapter-contract"], automaticTests: ["localDossierPipeline: fail closed", "localDossierBatch: 15 casi"] },
  { key: "deduplicate-queue", rule: "Clienti e input di coda duplicati non generano una seconda lavorazione.", registryRuleIds: ["system-single-active-practice", "system-atomic-checkpoint-resume"], automaticTests: ["executionPlan: deduplica", "localDossierBatch: duplicati e riavvio"] },
  { key: "manual-crm-comparison-scope", rule: "Confronto CRM manuale esclude impianto, risparmio, finestre protette e nei TEST fine lavori.", registryRuleIds: ["core-mapping-complete"], automaticTests: ["comparisonPolicy"] },
  { key: "crm-readonly-adapter", rule: "Adapter CRM APR configurabile soltanto GET/HEAD, senza credenziali o mutazioni e con gate globale chiuso.", registryRuleIds: ["system-apr-crm-readonly-adapter-contract", "system-apr-crm-integration-boundary"], automaticTests: ["aprCrmReadOnlyContract", "crmReadOnlyAdapter", "aprRuntimeDoctor", "localDashboardServer"] },
]);

/**
 * Impronta della sostanza delle regole, non soltanto del numero di versione.
 * In precedenza bastava dimenticare di incrementare la versione per mantenere
 * verde un'evidenza di test riferita a codice ormai diverso.
 */
export const APR_RULE_SOURCE_FINGERPRINT = crypto.createHash("sha256").update(JSON.stringify({
  matrix: APR_RULE_TEST_MATRIX,
  registry: ENEA_OPERATIONAL_REGISTRY.map((rule) => ({
    id: rule.id,
    step: rule.step,
    condition: rule.condition,
    sourcePrecedence: rule.sourcePrecedence,
    deterministicAction: rule.deterministicAction,
    outcome: rule.outcome,
    lifecycle: rule.lifecycle ?? null,
  })),
})).digest("hex");

export interface AprRuleMatrixEvidence {
  matrixVersion: typeof APR_RULE_TEST_MATRIX_VERSION;
  registryVersion: typeof ENEA_OPERATIONAL_REGISTRY_VERSION;
  verifiedAt: string;
  testCommand: string;
  passedKeys: string[];
  ruleProofs: Record<string, {
    fixtureId: string;
    independentAnalogFixtureId: string;
    sourceFingerprint: string;
    replayFingerprint: string;
    executionPath: string[];
    producedFields: string[];
    expectedOutcome: string;
    actualOutcome: string;
    positiveTest: string;
    negativeTest: string;
    codeFingerprint: string;
    verifiedAt: string;
  }>;
  sourceFingerprint: string;
  testExitCode: 0;
  deployment?: {
    verifiedAt: string;
    builtBundleSha256: Readonly<Record<string, string>>;
    installedBundleSha256: Readonly<Record<string, string>>;
  };
}

export function evaluateRuleMatrix(evidence: AprRuleMatrixEvidence | null) {
  const evidenceCurrent = evidence?.matrixVersion === APR_RULE_TEST_MATRIX_VERSION
    && evidence.registryVersion === ENEA_OPERATIONAL_REGISTRY_VERSION
    && evidence.sourceFingerprint === APR_RULE_SOURCE_FINGERPRINT
    && evidence.testExitCode === 0;
  const passed = new Set(evidenceCurrent ? evidence.passedKeys.filter((key) => Boolean(evidence.ruleProofs?.[key])) : []);
  const deploymentVerified = evidenceCurrent && evidence.deployment
    && Object.keys(evidence.deployment.builtBundleSha256).length > 0
    && Object.entries(evidence.deployment.builtBundleSha256)
      .every(([name, digest]) => evidence.deployment?.installedBundleSha256[name] === digest);
  return APR_RULE_TEST_MATRIX.map((entry) => ({
    ...entry,
    status: !passed.has(entry.key)
      ? "pending_test" as const
      : deploymentVerified
        ? "active_tested_deployed" as const
        : "tested_not_deployed" as const,
  }));
}
